version: '3.8'

services:
  tbrs-app:
    build: .
    ports:
      - "8089:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    # For Raspberry Pi, you might want to add resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    # Health check to ensure the app is running
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 